### ISSUE TITLE
Exception occurs "A task was canceled"

### ISSUE THREAD

**Issue by lightyou** [JaySmith/Marble#10]
An exception occured at Google API level.
This exception should be caught in Marble.

*************\* Exception Text **************
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Google.Apis.Requests.ClientServiceRequest`1.Execute() in c:\code\google.com\google-api-dotnet-client\default\Tools\Google.Apis.Release\bin\Debug\test\default\Src\GoogleApis\Apis\Requests\ClientServiceRequest.cs:line 93
   at Marble.Google.GoogleCalendarService.GetCalendarEntriesInRange() in c:\Solutions\Public\Marble\Marble\Google\GoogleCalendarService.cs:line 48
   at Marble.Google.GoogleCalendarService.GetAppointmentsInRange() in c:\Solutions\Public\Marble\Marble\Google\GoogleCalendarService.cs:line 55
   at Marble.CalendarSync.Sync() in c:\Solutions\Public\Marble\Marble\CalendarSync.cs:line 39
   at Marble.MarbleSync.SyncCalendar() in c:\Solutions\Public\Marble\Marble\MarbleSync.cs:line 29
   at Marble.NotificationIcon.Sync() in c:\Solutions\Public\Marble\Marble\NotificationIcon.cs:line 121
   at Marble.NotificationIcon.syncTimerTick(Object sender, EventArgs e) in c:\Solutions\Public\Marble\Marble\NotificationIcon.cs:line 41
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by JaySmith-zz** [comment]
@lightyou Please update to v0.1.4 and let me know if this problem still occurs.  I have not seen this one and I have been running it for about a week now.

**Comment by JaySmith-zz** [comment]
@lightyou any luck with a later version?

**Comment by lightyou** [comment]
Yes, the exception didn't occured with the 0.4.1. I had some other when network connection is lost (I have a laptop)  

```
 System.Net.Http.HttpRequestException: An error occurred while sending the request. --->    System.Net.WebException: The remote name could not be resolved: 'www.googleapis.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Google.Apis.Requests.ClientServiceRequest`1.Execute() in c:\code\google.com\google-api-dotnet-  client\default\Tools\Google.Apis.Release\bin\Debug\test\default\Src\GoogleApis\Apis\Requests\Clien  tServiceRequest.cs:line 93
   at Marble.Google.GoogleCalendarService.GetCalendarEntriesInRange()
   at Marble.Google.GoogleCalendarService.GetAppointmentsInRange()
   at Marble.CalendarSync.Sync()
   at Marble.NotificationIcon.syncTimerTick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr  lparam)
```

It would be nice this one to be caught.

Thank you for your help. I'm very happy with Marbel indeed.

**Comment by JaySmith-zz** [comment]
I agree, I will close this issue and add a new to our new support project issues.  We are working on adding more error handling and logging so we can track these issue down easier.

Thanks for your input.  Keep it coming.

Jay
