### ISSUE TITLE
Could not find file 'C:\Windows\system32\client_secrets.json'

### ISSUE THREAD

**Issue by JaySmith-zz** [JaySmith/Marble#8]
Periodically I get the following error:

Could not find file 'C:\Windows\system32\client_secrets.json'

just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Windows\system32\client_secrets.json'.
File name: 'C:\Windows\system32\client_secrets.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Marble.Google.GoogleClient.GetAuthorization() in c:\Solutions\Public\Marble\Marble\Google\GoogleClient.cs:line 45
   at Marble.Google.GoogleClient..ctor(String dataStoreFolderName) in c:\Solutions\Public\Marble\Marble\Google\GoogleClient.cs:line 34
   at Marble.CalendarSync..ctor() in c:\Solutions\Public\Marble\Marble\CalendarSync.cs:line 25
   at Marble.MarbleSync.SyncCalendar() in c:\Solutions\Public\Marble\Marble\MarbleSync.cs:line 28
   at Marble.NotificationIcon.Sync() in c:\Solutions\Public\Marble\Marble\NotificationIcon.cs:line 121
   at Marble.NotificationIcon.syncTimerTick(Object sender, EventArgs e) in c:\Solutions\Public\Marble\Marble\NotificationIcon.cs:line 41
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

Marble

**Comment by JaySmith-zz** [comment]
I am working on removing the code to read the ClientSecret and ClientId from the file and reading it from the app.config instead.  I have this working in a local branch and am running it locally.  I will merge and push as soon as I find out if it eliminates the issue.

**Comment by JaySmith-zz** [comment]
Fix confirmed.  Code is in remote repository
